### ISSUE TITLE
Running `$ npm i -D webpack-extension-manifest-plugin` has some errors on Windows 10

### ISSUE THREAD

**Issue by tagnja** [Scrum/webpack-extension-manifest-plugin#32]
Error 1: 
MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

Error 2: 
MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found.

I have the following questions, can you help me.

Is the project compatible with Windows? 

What environments are needed for using this project on Windows?

**Comment by Scrum** [comment]
> Is the project compatible with Windows?

no information

> What environments are needed for using this project on Windows?

nodejs v8 and up
